version: '3.8'

services:
  
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "33060:3306"
    
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: gestion_cartuchos_app
    env_file:
      - .env
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
      MY_ALLOW_SPECIFIC_ORIGINS: ${MY_ALLOW_SPECIFIC_ORIGINS}
      
    ports:
      - "5204:5204"
    depends_on:
      - mysql-db
    networks:
      - app-network
    

  frontend:
    build:
      context: ../Gestion_Cartuchos_Frontend  
    container_name: gestion_cartuchos_frontend
    ports:
      - "80:80"  # Nginx servirá la app en el puerto 80
    depends_on: 
      - "app"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
